## see README
# if you want to use the low level CTAPI interface instead of the advanced PCSC interface
# uncomment the following line.
#CTAPI = -DCTAPI

ifndef CTAPI # PCSC
	PCSC_CFLAGS = -I/usr/include/PCSC
	PCSC_LDFLAGS = -lpcsclite
else # CTAPI
	USB_CFLAGS =
	USB_LDFLAGS = -lusb-1.0
endif

#if __SYNC_ADD_AND_FETCH is not available set HAVE_SYNC_ADD_AND_FETCH=0
#debug
CFLAGS = -g -DDEBUG -DHAVE_SYNC_ADD_AND_FETCH=1 $(CTAPI)
#relase
#CFLAGS = -O2 -DHAVE_SYNC_ADD_AND_FETCH=1 $(CTAPI)
